import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Router, { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    router.push("/brand-management/brands/");
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Shout Interactive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}></div>
    </div>
  );
}
