import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Router, { useRouter } from "next/router";
import { useEffect } from "react";
import CircularProgress from "@mui/material/CircularProgress";

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    router.push("/auth/login");
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Shout Interactive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <div className="mx-auto my-auto grid justify-items-center justify-center mt-[300px]">
          <CircularProgress color="inherit" />
        </div>
      </div>
    </div>
  );
}
